export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHARGE_LOADING = 'CHARGE_LOADING';
export const CHARGE_LOADED = 'CHARGE_LOADED';
export const CHARGE_LOAD_ERROR = 'CHARGE_LOAD_ERROR';

export const KEYWORD_LOADING = 'KEYWORD_LOADING';
export const KEYWORD_LOADED = 'KEYWORD_LOADED';
export const KEYWORD_LOAD_ERROR = 'KEYWORD_LOAD_ERROR';
export const KEYWORD_ADD_TO_BLACK_REQUEST = 'KEYWORD_ADD_TO_BLACK_REQUEST';
export const KEYWORD_ADD_TO_BLACK_SUCCESS = 'KEYWORD_ADD_TO_BLACK_SUCCESS';
export const KEYWORD_ADD_TO_BLACK_ERROR = 'KEYWORD_ADD_TO_BLACK_ERROR';
export const KEYWORD_DEL_REQUEST = 'KEYWORD_DEL_REQUEST';
export const KEYWORD_DEL_SUCCESS = 'KEYWORD_DEL_SUCCESS';
export const KEYWORD_DEL_ERROR = 'KEYWORD_DEL_ERROR';