export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHARGE_LOADING = 'CHARGE_LOADING';
export const CHARGE_LOADED = 'CHARGE_LOADED';
export const CHARGE_LOAD_ERROR = 'CHARGE_LOAD_ERROR';